### ISSUE TITLE
`results/` dir isn't auto-created

### ISSUE THREAD

**Issue by kousu** [santropolroulant/smell-test#2]
I got

```
./testssl.sh/testssl.sh: ligne 895: results/ac.duckduckgo.com_20180307-190353.json: Aucun fichier ou dossier de ce type
```

This is because `log_dir` is never created.

You can use `os.makedirs(log_dir)` to ensure it is created.

While I'm at it, on Linux the proper location for this, according to the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) should be `~/.cache/smell-test` (actually `$XDG_CACHE_HOME/smell-test`). There's a small [python lib](https://pypi.python.org/pypi/pyxdg) which gives you `xdg.BaseDirectory.xdg_cache_home` I don't know what OS X should do, but writing into the same location as the code is slightly risky. **EDIT**: [here's what SO thinks](https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x)

**Comment by johnsaigle** [comment]
Cool this seems like an easy change.

> I don't know what OS X should do

This script is meant to be run on a router so I don't think we have to worry about this. I'm developing on Debian anyway so if you put this note in here for me than don't worry about it 😛
