### ISSUE TITLE
Write against python2/3

### ISSUE THREAD

**Issue by kousu** [santropolroulant/smell-test#8]
There's a good guide to being cross-compatible here: http://python-future.org/compatible_idioms.html

**Comment by kousu** [comment]
Oh, I just realized that scapy hasn't been ported to python3. Instead there's a fork called [scapy3k](https://github.com/phaethon/scapy).

I don't know how incompatible it is. Maybe it's not a big deal---just

```
try:
  import scapy3k as scapy
except ImportError:
  import scapy
```
but maybe it's too much.

*if* I had my vote, I would write against scapy3k and drop python2 support. python3 is well-established at this point.

**Comment by johnsaigle** [comment]
So to be clear the preference is to switch to python 3 only and use the scapy3k library?

**Comment by johnsaigle** [comment]
Closing this because we are now writing for Python3 only.
